#!/usr/bin/env bash
# inventory-vps.sh — chạy trên VPS qua SSH, output ra markdown để LEAD review.
#
# Usage (từ máy LEAD):
#   scp tools/deploy/inventory-vps.sh root@<droplet-ip>:/tmp/
#   ssh root@<droplet-ip> 'bash /tmp/inventory-vps.sh' > tools/deploy/VPS-INVENTORY.md
#   # Sau đó review file VPS-INVENTORY.md, điền 3 quyết định nginx/cert/data ở cuối.
#
# Yêu cầu: chạy với quyền root (hoặc sudo) để xem được /etc/letsencrypt, ufw, systemctl status.
# KHÔNG modify gì trên VPS — chỉ đọc state.

set -u  # KHÔNG dùng -e, để các check fail không dừng script

section() { printf '\n## %s\n\n' "$1"; }
codeblock_start() { printf '```\n'; }
codeblock_end() { printf '```\n'; }
run() { printf '$ %s\n' "$*"; "$@" 2>&1 || true; }

printf '# VPS Inventory (MEPAuto) — %s\n' "$(date -Iseconds)"
printf '\n_Generated by `tools/deploy/inventory-vps.sh`. Review + confirm 3 quyết định cuối file._\n'
printf '\n**Lưu ý:** VPS này đã chạy EPAuto (port 8080). MEPAuto sẽ dùng port 8081.\n'

section "1. OS + tài nguyên"
codeblock_start
run uname -a
run lsb_release -a
run df -h
run free -m
codeblock_end

section "2. Docker + Compose"
codeblock_start
if command -v docker >/dev/null 2>&1; then
    run docker --version
    run docker ps -a
    run docker network ls
    run docker volume ls
else
    echo "MISSING: docker"
fi
if command -v docker-compose >/dev/null 2>&1; then
    run docker-compose --version
elif docker compose version >/dev/null 2>&1; then
    run docker compose version
else
    echo "MISSING: compose"
fi
codeblock_end

section "3. Nginx"
codeblock_start
if command -v nginx >/dev/null 2>&1; then
    run nginx -v
    run systemctl status nginx --no-pager -l
    echo
    echo "--- /etc/nginx/sites-enabled/ ---"
    run ls -la /etc/nginx/sites-enabled/
    echo
    echo "--- /etc/nginx/conf.d/ ---"
    run ls -la /etc/nginx/conf.d/
    echo
    echo "--- nginx config test ---"
    run nginx -t
else
    echo "MISSING: nginx (system-level)"
fi
codeblock_end

section "4. Cert Let's Encrypt"
codeblock_start
if command -v certbot >/dev/null 2>&1; then
    run certbot --version
    echo
    echo "--- /etc/letsencrypt/live/ ---"
    run ls -la /etc/letsencrypt/live/
    echo
    run certbot certificates
else
    echo "MISSING: certbot"
fi
codeblock_end

section "5. Firewall"
codeblock_start
if command -v ufw >/dev/null 2>&1; then
    run ufw status verbose
else
    echo "ufw not installed, dumping iptables instead:"
    run iptables -L -n
fi
codeblock_end

section "6. Port đang nghe (80/443/8080/8081)"
codeblock_start
run ss -tlnp
codeblock_end

section "7. EPAuto service đang chạy (kiểm tra không conflict)"
codeblock_start
echo "--- EPAuto containers ---"
docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}' 2>/dev/null | grep -iE 'epauto' || echo "(không tìm thấy epauto container)"
echo
echo "--- Port 8080 (EPAuto) ---"
run ss -tlnp | grep ':8080' || echo "(port 8080 free)"
echo
echo "--- Port 8081 (MEPAuto target) ---"
run ss -tlnp | grep ':8081' || echo "(port 8081 free — OK cho MEPAuto)"
codeblock_end

section "8. Folder dữ liệu"
codeblock_start
echo "--- /var/mepauto-data (MEPAuto target) ---"
if [ -d /var/mepauto-data ]; then
    run ls -la /var/mepauto-data
    run du -sh /var/mepauto-data
else
    echo "/var/mepauto-data: không tồn tại → sẽ tạo mới khi deploy"
fi
echo
echo "--- /var/data (EPAuto, kiểm tra không conflict) ---"
if [ -d /var/data ]; then
    run ls -la /var/data
    run du -sh /var/data
else
    echo "/var/data: không tồn tại"
fi
echo
echo "--- /opt/mepauto và /opt/epauto ---"
run bash -c "ls -la /opt/ 2>/dev/null | grep -iE 'mepauto|epauto' || echo '(chưa có)'"
codeblock_end

section "9. .NET runtime"
codeblock_start
if command -v dotnet >/dev/null 2>&1; then
    run dotnet --list-runtimes
else
    echo "dotnet không có trong PATH (ok nếu app trong Docker)"
fi
codeblock_end

section "10. JWT env vars (key names only)"
codeblock_start
echo "(kiểm tra không leak key — chỉ liệt kê tên var)"
if command -v docker >/dev/null 2>&1; then
    docker ps --format '{{.Names}}' 2>/dev/null | while read -r container; do
        echo "--- $container env (key names only) ---"
        docker exec "$container" env 2>/dev/null | awk -F= '{print $1}' | grep -iE 'jwt|secret|signing|token' || echo "(không có match)"
    done
fi
codeblock_end

# ============================================================
printf '\n---\n\n'
section "Quyết định LEAD (điền sau khi review output ở trên)"
cat <<'EOF'
> Sau khi review các section trên, LEAD chốt các quyết định bên dưới và commit file này vào repo.

### N.1. Nginx — system-level (recommended cho shared VPS)

- VPS đã có nginx system serving EPAuto → MEPAuto dùng variant "system".
- [ ] Đã thêm site `/etc/nginx/sites-available/mepauto-api.conf` (từ nginx-system-site.conf.template).
- [ ] Đã sửa domain placeholder → domain thực tế.
- [ ] `nginx -t && systemctl reload nginx` OK.

### N.2. Port allocation

- [ ] Port 8080 = EPAuto (đã verify ở section 7).
- [ ] Port 8081 = MEPAuto (free, xác nhận ở section 6).

### N.3. /var/mepauto-data

- [ ] (a) **Tạo mới** — fresh deploy, không có data cũ.
- [ ] (b) **Giữ nguyên** — đã có data, kiểm tra schema OK.

### N.4. JWT signing key

- [ ] Tạo mới key 32-byte bằng `openssl rand -base64 48` → điền vào .env.
- [ ] Lưu key backup ở nơi an toàn (password manager, không commit git).

### N.5. Deploy path trên VPS

- [ ] MEPAuto repo code tại: `/opt/mepauto` (hoặc điền path thực tế):
EOF
echo
echo "_Kết thúc inventory. Commit file này vào repo dưới tên \`tools/deploy/VPS-INVENTORY.md\`._"
